# Generated by Django 3.2.5 on 2021-07-11 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monopoly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardset',
            fields=[
                ('cardset_name', models.CharField(help_text='請輸入卡片集名稱', max_length=10)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='卡片及的獨特id', primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChanceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', help_text='請輸入機會內容的描述', max_length=200)),
                ('money_deduction', models.IntegerField(default=0, help_text='請輸入減少的金錢數目')),
                ('stop_round', models.IntegerField(default=0, help_text='請輸入暫停的回合數目')),
                ('cardset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monopoly.cardset')),
            ],
        ),
    ]
