# Generated by Django 3.2.5 on 2021-07-12 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0002_cardset_chancecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='卡片集的獨特id', primary_key=True, serialize=False),
        ),
    ]
