# Generated by Django 3.2.5 on 2021-07-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0004_auto_20210719_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_type', models.CharField(help_text='請輸入土地的種類', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(help_text='土地的位置')),
                ('description', models.CharField(help_text='請輸入土地的描述', max_length=20)),
                ('value', models.IntegerField(help_text='不特定的數值')),
                ('_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monopoly.map')),
                ('land_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monopoly.landtype')),
            ],
        ),
    ]
