# Generated by Django 3.2.5 on 2021-07-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0005_land_landtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='value',
            field=models.IntegerField(help_text='不特定的數值', null=True),
        ),
    ]
