# Generated by Django 3.2.5 on 2021-07-21 12:13

from django.db import migrations, models
import django.utils.timezone
import monopoly.models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0007_alter_land_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=monopoly.models.map_lands_path),
            preserve_default=False,
        ),
    ]
