# Generated by Django 3.2.5 on 2021-07-22 08:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0013_land_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='color',
            field=colorfield.fields.ColorField(default='#955436', max_length=18),
        ),
    ]
