# Generated by Django 3.2.5 on 2021-07-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0023_alter_land_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.CharField(default='', help_text='請輸入土地的描述', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='value',
            field=models.IntegerField(blank=True, default=0, help_text='不特定的數值', null=True),
        ),
    ]
