# Generated by Django 3.2.5 on 2021-07-26 01:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0025_alter_land_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#955436', max_length=18, null=True),
        ),
    ]
