# Generated by Django 3.2.5 on 2021-08-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0027_alter_map_cardsets'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefineVariableName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_1_name', models.CharField(blank=True, default='', help_text='請輸入自訂變數一在遊戲中的名稱', max_length=10, null=True)),
                ('variable_2_name', models.CharField(blank=True, default='', help_text='請輸入自訂變數二在遊戲中的名稱', max_length=10, null=True)),
                ('variable_3_name', models.CharField(blank=True, default='', help_text='請輸入自訂變數三在遊戲中的名稱', max_length=10, null=True)),
                ('variable_4_name', models.CharField(blank=True, default='', help_text='請輸入自訂變數四在遊戲中的名稱', max_length=10, null=True)),
                ('variable_5_name', models.CharField(blank=True, default='', help_text='請輸入自訂變數五在遊戲中的名稱', max_length=10, null=True)),
                ('_map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monopoly.map')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefineVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_1', models.IntegerField(blank=True, default=0, null=True)),
                ('variable_2', models.IntegerField(blank=True, default=0, null=True)),
                ('variable_3', models.IntegerField(blank=True, default=0, null=True)),
                ('variable_4', models.IntegerField(blank=True, default=0, null=True)),
                ('variable_5', models.IntegerField(blank=True, default=0, null=True)),
                ('_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monopoly.map')),
            ],
        ),
    ]
