# Generated by Django 3.2.5 on 2021-08-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0028_userdefinevariable_userdefinevariablename'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefinevariablename',
            name='variable_1_default',
            field=models.IntegerField(blank=True, default=0, help_text='請輸入自訂變數一的初始值', null=True),
        ),
        migrations.AddField(
            model_name='userdefinevariablename',
            name='variable_2_default',
            field=models.IntegerField(blank=True, default=0, help_text='請輸入自訂變數二的初始值', null=True),
        ),
        migrations.AddField(
            model_name='userdefinevariablename',
            name='variable_3_default',
            field=models.IntegerField(blank=True, default=0, help_text='請輸入自訂變數三的初始值', null=True),
        ),
        migrations.AddField(
            model_name='userdefinevariablename',
            name='variable_4_default',
            field=models.IntegerField(blank=True, default=0, help_text='請輸入自訂變數四的初始值', null=True),
        ),
        migrations.AddField(
            model_name='userdefinevariablename',
            name='variable_5_default',
            field=models.IntegerField(blank=True, default=0, help_text='請輸入自訂變數五的初始值', null=True),
        ),
    ]
