# Generated by Django 3.2.5 on 2021-08-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0029_auto_20210801_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_1_name',
            field=models.CharField(blank=True, default='變數一', help_text='請輸入自訂變數一在遊戲中的名稱', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_2_name',
            field=models.CharField(blank=True, default='變數二', help_text='請輸入自訂變數二在遊戲中的名稱', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_3_name',
            field=models.CharField(blank=True, default='變數三', help_text='請輸入自訂變數三在遊戲中的名稱', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_4_name',
            field=models.CharField(blank=True, default='變數四', help_text='請輸入自訂變數四在遊戲中的名稱', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_5_name',
            field=models.CharField(blank=True, default='變數五', help_text='請輸入自訂變數五在遊戲中的名稱', max_length=10, null=True),
        ),
    ]
