# Generated by Django 3.2.5 on 2021-08-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0032_userdefinevariable_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='cardsets',
            field=models.ManyToManyField(blank=True, help_text='選擇所包含的卡片集', to='monopoly.Cardset'),
        ),
    ]
