# Generated by Django 3.2.5 on 2021-08-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0035_userdefinevariable_player_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='variable_1_change',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='land',
            name='variable_2_change',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='land',
            name='variable_3_change',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='land',
            name='variable_4_change',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='land',
            name='variable_5_change',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
