# Generated by Django 3.2.5 on 2021-08-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0037_alter_land_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
