# Generated by Django 3.2.5 on 2021-08-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0038_alter_land_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='modal_message',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
