# Generated by Django 3.2.5 on 2021-08-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0040_alter_land_modal_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='is_use_upload_image',
            field=models.BooleanField(default=False, help_text='是否使用自訂圖片'),
        ),
    ]
