# Generated by Django 3.2.5 on 2021-08-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0041_land_is_use_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='is_use_upload_image',
            field=models.BooleanField(default=False),
        ),
    ]
