# Generated by Django 3.2.5 on 2021-08-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0042_alter_land_is_use_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='cardset_name',
            field=models.CharField(help_text='請輸入卡片集名稱', max_length=20),
        ),
    ]
