# Generated by Django 3.2.5 on 2021-08-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0043_alter_cardset_cardset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='modal_message',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
    ]
