# Generated by Django 3.2.5 on 2021-08-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0044_alter_land_modal_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='modal_message',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
