# Generated by Django 3.2.5 on 2021-08-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0046_map_rolled_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='rolled_rule_blockly',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='map',
            name='rolled_rule',
            field=models.TextField(default="if money < 0:\n\tis_game_end = 'true'", max_length=2000),
        ),
    ]
