# Generated by Django 3.2.5 on 2021-08-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0047_auto_20210822_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='chancecard',
            name='subtitle',
            field=models.CharField(default='', help_text='請輸入副標題', max_length=15),
        ),
        migrations.AddField(
            model_name='chancecard',
            name='title',
            field=models.CharField(default='', help_text='請輸入標題', max_length=15),
        ),
        migrations.AddField(
            model_name='chancecard',
            name='variable_1_change',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chancecard',
            name='variable_2_change',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chancecard',
            name='variable_3_change',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chancecard',
            name='variable_4_change',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chancecard',
            name='variable_5_change',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='map',
            name='rolled_rule',
            field=models.TextField(default='if money < 0:\n\tself.trigger_event_type = "rule_end_game"', max_length=2000),
        ),
        migrations.AlterField(
            model_name='map',
            name='rolled_rule_blockly',
            field=models.TextField(default='<xml xmlns="https://developers.google.com/blockly/xml"><block type="start_block" id="03a@MMxf9QjZV_?noz}U" x="70" y="37"><next><block type="controls_if" id=",@hO`QW+#-8*W/VET-yQ"><value name="IF0"><block type="variable_vs_number" id="#TwWZ5u[=L;BRrq7W~(r"><field name="choice_1">money</field><field name="compare">@#%!less@#%!</field><field name="number">0</field></block></value><statement name="DO0"><block type="end_game_event" id="^X!K,51$lpF4/QmfK+KZ"></block></statement></block></next></block></xml>', max_length=100000),
        ),
    ]
