# Generated by Django 3.2.5 on 2021-08-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0048_auto_20210825_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chancecard',
            name='subtitle',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='chancecard',
            name='title',
            field=models.CharField(default='', max_length=15),
        ),
    ]
