# Generated by Django 3.2.5 on 2021-08-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0049_auto_20210825_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chancecard',
            name='description',
            field=models.TextField(blank=True, default='', help_text='請輸入機會內容的描述', max_length=200),
        ),
        migrations.AlterField(
            model_name='chancecard',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
