# Generated by Django 3.2.5 on 2021-08-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0050_auto_20210825_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chancecard',
            name='title',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
