# Generated by Django 3.2.5 on 2021-08-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0051_alter_chancecard_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chancecard',
            name='title',
            field=models.CharField(default='', max_length=15),
        ),
    ]
