# Generated by Django 3.2.5 on 2021-08-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0054_auto_20210830_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chancecard',
            name='multiple_choice_1',
        ),
        migrations.RemoveField(
            model_name='chancecard',
            name='multiple_choice_2',
        ),
        migrations.RemoveField(
            model_name='chancecard',
            name='multiple_choice_3',
        ),
        migrations.RemoveField(
            model_name='chancecard',
            name='multiple_choice_4',
        ),
        migrations.AddField(
            model_name='chancecard',
            name='multiple_choices',
            field=models.JSONField(blank=True, default={'answer': '', 'choice_1': '', 'choice_2': '', 'choice_3': '', 'choice_4': ''}),
        ),
    ]
