# Generated by Django 3.2.5 on 2021-08-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0055_auto_20210830_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chancecard',
            name='multiple_choices',
        ),
        migrations.AddField(
            model_name='chancecard',
            name='multiple_choice_1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chancecard',
            name='multiple_choice_2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chancecard',
            name='multiple_choice_3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chancecard',
            name='multiple_choice_4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chancecard',
            name='multiple_choice_answer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
