# Generated by Django 3.2.5 on 2021-08-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0056_auto_20210830_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chancecard',
            name='multiple_choice_answer',
            field=models.IntegerField(default=1),
        ),
    ]
