# Generated by Django 3.2.5 on 2021-08-31 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0060_alter_chancecard_multiple_choice_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBoardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prior_variable', models.CharField(default='money', max_length=30)),
                ('is_descending_order', models.BooleanField(default=True)),
                ('background_img_url', models.CharField(blank=True, default='', max_length=200)),
                ('score_board_sound_effect', models.CharField(blank=True, default='', max_length=200)),
                ('_map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monopoly.map')),
            ],
        ),
    ]
