# Generated by Django 3.2.5 on 2021-08-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0061_scoreboardsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboardsetting',
            name='prior_variable',
            field=models.CharField(default='asset', max_length=30),
        ),
    ]
