# Generated by Django 3.2.5 on 2021-08-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0062_alter_scoreboardsetting_prior_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboardsetting',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='scoreboardsetting',
            name='title',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
