# Generated by Django 3.2.5 on 2021-09-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0063_auto_20210831_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboardsetting',
            name='score_board_sound_effect',
            field=models.CharField(blank=True, default='background', max_length=200),
        ),
        migrations.AlterField(
            model_name='scoreboardsetting',
            name='subtitle',
            field=models.CharField(blank=True, default='Good Game!', max_length=15),
        ),
        migrations.AlterField(
            model_name='scoreboardsetting',
            name='title',
            field=models.CharField(blank=True, default='計分板', max_length=15),
        ),
    ]
