# Generated by Django 3.2.5 on 2021-09-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0064_auto_20210901_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(upload_to='avatar/'),
        ),
    ]
