# Generated by Django 3.2.5 on 2021-09-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0065_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='musicAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('credit_url', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='musicCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('path', models.CharField(default='', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monopoly.musicauthor')),
            ],
        ),
    ]
