# Generated by Django 3.2.5 on 2021-09-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0066_musicauthor_musiccollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboardsetting',
            name='audio_url',
            field=models.CharField(blank=True, default='default/background.mp3', max_length=500),
        ),
        migrations.AlterField(
            model_name='scoreboardsetting',
            name='background_img_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='scoreboardsetting',
            name='score_board_sound_effect',
            field=models.CharField(blank=True, default='background', max_length=500),
        ),
    ]
