# Generated by Django 3.2.5 on 2021-09-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0067_auto_20210904_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(default='', max_length=500)),
                ('money_deduction', models.CharField(default='', max_length=500)),
                ('money_addition', models.CharField(default='', max_length=500)),
                ('dice', models.CharField(default='', max_length=500)),
                ('hover_button', models.CharField(default='', max_length=500)),
                ('player_move', models.CharField(default='', max_length=500)),
                ('player_teleport', models.CharField(default='', max_length=500)),
                ('player_turn_over', models.CharField(default='', max_length=500)),
                ('user_define_1', models.CharField(default='', max_length=500)),
                ('user_define_2', models.CharField(default='', max_length=500)),
                ('user_define_3', models.CharField(default='', max_length=500)),
                ('_map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monopoly.map')),
            ],
        ),
    ]
