# Generated by Django 3.2.5 on 2021-09-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0070_auto_20210908_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicsetting',
            name='build',
            field=models.CharField(blank=True, default='預設', max_length=500),
        ),
    ]
