# Generated by Django 3.2.5 on 2021-09-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0071_musicsetting_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicauthor',
            name='credit_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
