# Generated by Django 3.2.5 on 2021-09-10 08:34

from django.db import migrations, models
import django.db.models.deletion
import monopoly.models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0072_alter_musicauthor_credit_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackGroundSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_img_url', models.CharField(blank=True, default='預設', max_length=500)),
                ('tile_backgrounf_img', models.ImageField(blank=True, default='', null=True, upload_to=monopoly.models.map_background_path)),
                ('_map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monopoly.map')),
            ],
        ),
    ]
