# Generated by Django 3.2.5 on 2021-09-10 08:39

from django.db import migrations, models
import monopoly.models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0073_backgroundsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundsetting',
            name='tile_backgrounf_img',
        ),
        migrations.AddField(
            model_name='backgroundsetting',
            name='tile_background_img',
            field=models.ImageField(blank=True, default='預設', null=True, upload_to=monopoly.models.map_background_path),
        ),
    ]
