# Generated by Django 3.2.5 on 2021-09-10 08:57

from django.db import migrations, models
import monopoly.models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0074_auto_20210910_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundsetting',
            name='tile_background_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to=monopoly.models.map_background_path),
        ),
    ]
