# Generated by Django 3.2.5 on 2021-09-20 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0079_alter_backgroundsetting_tile_background_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_initial', models.IntegerField(default=1500, help_text='請輸入每位玩家的起始金額')),
                ('ratio_rent_to_price_for_house', models.IntegerField(default=4)),
                ('ratio_rent_to_price_for_hotel', models.IntegerField(default=2)),
                ('hoouse_construction_cost', models.IntegerField(default=100)),
                ('hotel_construction_cost', models.IntegerField(default=150)),
                ('money_pass_start', models.IntegerField(default=200, help_text='請輸入通過起點的獎金')),
                ('_map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monopoly.map')),
            ],
        ),
    ]
