# Generated by Django 3.2.5 on 2021-09-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0080_basicsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicsetting',
            old_name='hoouse_construction_cost',
            new_name='house_construction_cost',
        ),
    ]
