# Generated by Django 3.2.5 on 2021-09-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0082_auto_20210923_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsetting',
            name='ratio_rent_vs_price_infra',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='rent_constant_infra',
            field=models.IntegerField(default=0),
        ),
    ]
