# Generated by Django 3.2.5 on 2021-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0083_auto_20210926_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsetting',
            name='game_process',
            field=models.TextField(blank=True, default='踩到監獄或是抽到監獄事件時你可能會被關到監獄(暫停回合)\n                     當有一位玩家破產時，遊戲結束', max_length=500),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='welcome_info',
            field=models.CharField(default='歡迎來到大富翁遊戲', max_length=15),
        ),
    ]
