# Generated by Django 3.2.5 on 2021-10-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0085_alter_basicsetting_game_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicsetting',
            name='volume_background',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='musicsetting',
            name='volume_build',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='musicsetting',
            name='volume_dice',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='musicsetting',
            name='volume_hover_button',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='musicsetting',
            name='volume_money_addition',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='musicsetting',
            name='volume_money_deduction',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='musicsetting',
            name='volume_player_move',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='musicsetting',
            name='volume_player_teleport',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='musicsetting',
            name='volume_player_turn_over',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='musicsetting',
            name='volume_user_define_1',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='musicsetting',
            name='volume_user_define_2',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='musicsetting',
            name='volume_user_define_3',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_1_default',
            field=models.IntegerField(blank=True, default=0, help_text='請輸入自訂變數x1的初始值', null=True),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_1_name',
            field=models.CharField(blank=True, default='', help_text='請輸入自訂變數x1在遊戲中的名稱', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_2_default',
            field=models.IntegerField(blank=True, default=0, help_text='請輸入自訂變數x2的初始值', null=True),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_2_name',
            field=models.CharField(blank=True, default='', help_text='請輸入自訂變數x2在遊戲中的名稱', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_3_default',
            field=models.IntegerField(blank=True, default=0, help_text='請輸入自訂變數x3的初始值', null=True),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_3_name',
            field=models.CharField(blank=True, default='', help_text='請輸入自訂變數x3在遊戲中的名稱', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_4_default',
            field=models.IntegerField(blank=True, default=0, help_text='請輸入自訂變數x4的初始值', null=True),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_4_name',
            field=models.CharField(blank=True, default='', help_text='請輸入自訂變數x4在遊戲中的名稱', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_5_default',
            field=models.IntegerField(blank=True, default=0, help_text='請輸入自訂變數x5的初始值', null=True),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_5_name',
            field=models.CharField(blank=True, default='', help_text='請輸入自訂變數x5在遊戲中的名稱', max_length=10),
        ),
    ]
