# Generated by Django 3.2.5 on 2021-10-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0086_auto_20211002_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicsetting',
            name='volume_background',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='musicsetting',
            name='volume_build',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='musicsetting',
            name='volume_dice',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='musicsetting',
            name='volume_hover_button',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='musicsetting',
            name='volume_money_addition',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='musicsetting',
            name='volume_money_deduction',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='musicsetting',
            name='volume_player_move',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='musicsetting',
            name='volume_player_teleport',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='musicsetting',
            name='volume_player_turn_over',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='musicsetting',
            name='volume_user_define_1',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='musicsetting',
            name='volume_user_define_2',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='musicsetting',
            name='volume_user_define_3',
            field=models.IntegerField(default=100),
        ),
    ]
