# Generated by Django 3.2.5 on 2021-10-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0087_auto_20211003_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='additional_parameter',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
