# Generated by Django 3.2.5 on 2021-10-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0090_alter_basicsetting_ratio_rent_vs_price_infra_for_same_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsetting',
            name='num_of_house_equal_hotel',
            field=models.IntegerField(default=3),
        ),
    ]
