# Generated by Django 3.2.5 on 2021-10-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0091_basicsetting_num_of_house_equal_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicsetting',
            name='house_construction_cost',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='basicsetting',
            name='money_initial',
            field=models.IntegerField(default=15000),
        ),
        migrations.AlterField(
            model_name='basicsetting',
            name='money_pass_start',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='basicsetting',
            name='num_of_house_equal_hotel',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='basicsetting',
            name='ratio_rent_vs_price',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='basicsetting',
            name='ratio_rent_vs_price_for_house',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='basicsetting',
            name='ratio_rent_vs_price_infra',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='basicsetting',
            name='ratio_rent_vs_price_infra_for_same_category',
            field=models.FloatField(default=0.125),
        ),
        migrations.AlterField(
            model_name='chancecard',
            name='money_addition',
            field=models.CharField(default='0', help_text='請輸入增加的金錢數目', max_length=30),
        ),
        migrations.AlterField(
            model_name='chancecard',
            name='money_deduction',
            field=models.CharField(default='0', help_text='請輸入減少的金錢數目', max_length=30),
        ),
        migrations.AlterField(
            model_name='scoreboardsetting',
            name='audio_url',
            field=models.CharField(blank=True, default='default/bgm/background.mp3', max_length=500),
        ),
    ]
