# Generated by Django 3.2.5 on 2021-10-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0093_auto_20211017_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='map_name',
            field=models.CharField(help_text='請輸入地圖名稱', max_length=20),
        ),
        migrations.AlterField(
            model_name='map',
            name='rolled_rule',
            field=models.TextField(default='\nif money < 0:\n  self.trigger_event_type = "rule_end_game"\nif x1 == 1:\n  x1 = 0\n  curr_player.set_variable_1(x1)\n  self.rolled_money_and_variables["x1"] = x1\n  self.trigger_event_type = "teleport"\n  self.trigger_event_title = "進牢"\n  self.trigger_event_message = "要好好反省喔"\n  self.trigger_event_subtitle = "真是不幸"\n  self.trigger_event_value = "10"\nif x2 == 1:\n  x2 = 0\n  curr_player.set_variable_2(x2)\n  self.rolled_money_and_variables["x2"] = x2\n  self.trigger_event_type = "move_to"\n  self.trigger_event_title = ""\n  self.trigger_event_message = "您前進到了民族路"\n  self.trigger_event_subtitle = ""\n  self.trigger_event_value = "11"\nif x2 == 2:\n  x2 = 0\n  curr_player.set_variable_2(x2)\n  self.rolled_money_and_variables["x2"] = x2\n  self.trigger_event_type = "move_to"\n  self.trigger_event_title = ""\n  self.trigger_event_message = "您前進到了博愛路"\n  self.trigger_event_subtitle = ""\n  self.trigger_event_value = "24"\n', max_length=2000),
        ),
        migrations.AlterField(
            model_name='map',
            name='rolled_rule_blockly',
            field=models.TextField(default='<xml xmlns="https://developers.google.com/blockly/xml"><block type="start_block" id="03a@MMxf9QjZV_?noz}U" x="70" y="37"><next><block type="controls_if" id=",@hO`QW+#-8*W/VET-yQ"><value name="IF0"><block type="variable_vs_number" id="#TwWZ5u[=L;BRrq7W~(r"><field name="choice_1">money</field><field name="compare">@#%!less@#%!</field><field name="number">0</field></block></value><statement name="DO0"><block type="end_game_event" id="^X!K,51$lpF4/QmfK+KZ"></block></statement><next><block type="controls_if" id="Nm]z%p$]!UG}aNkF8xh="><value name="IF0"><block type="variable_vs_number" id="=2G$wt_Hr~zmxwxjLYsl"><field name="choice_1">x1</field><field name="compare">==</field><field name="number">1</field></block></value><statement name="DO0"><block type="set_user_define_variable" id="MUKhhFu71vOYQddnkyLf"><field name="variable">x1</field><value name="value"><block type="math_number" id="[w8.5%eQCS:/TIv|3xH`"><field name="NUM">0</field></block></value><next><block type="teleport_event" id="L/]EMXqWE0L$jX$~[e0B"><field name="position">10</field><field name="title">進牢</field><field name="subtitle">真是不幸</field><field name="message">要好好反省喔</field></block></next></block></statement><next><block type="controls_if" id=",)5-kHgO]SRen?ruw_1~"><value name="IF0"><block type="variable_vs_number" id="7-04l9jsL%AeN*^5#+G)"><field name="choice_1">x2</field><field name="compare">==</field><field name="number">1</field></block></value><statement name="DO0"><block type="set_user_define_variable" id="]mLQ}Zg6^Tzx:D9rMD!|"><field name="variable">x2</field><value name="value"><block type="math_number" id="oTd.O-?q4BL]vqY!r7(J"><field name="NUM">0</field></block></value><next><block type="move_to_event" id="$=|{T,bd0ZF~C$rhbLxQ"><field name="position">11</field><field name="title"></field><field name="subtitle"></field><field name="message">您前進到了民族路</field></block></next></block></statement><next><block type="controls_if" id="XNZt-s-OzZ}(I}HYbR!c"><value name="IF0"><block type="variable_vs_number" id="KovEOCX#cF,c/p0P300u"><field name="choice_1">x2</field><field name="compare">==</field><field name="number">2</field></block></value><statement name="DO0"><block type="set_user_define_variable" id="(F`fksCpZE(3bwmlp_9:"><field name="variable">x2</field><value name="value"><block type="math_number" id="@!U*0@.;$lx0aq+NTr78"><field name="NUM">0</field></block></value><next><block type="move_to_event" id="g^C^$4DP*`tk1pqEcOx~"><field name="position">24</field><field name="title"></field><field name="subtitle"></field><field name="message">您前進到了博愛路</field></block></next></block></statement></block></next></block></next></block></next></block></next></block></xml>', max_length=100000),
        ),
    ]
