# Generated by Django 3.2.5 on 2021-10-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0094_auto_20211019_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='background_img_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
