# Generated by Django 3.2.5 on 2021-10-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0096_basicsetting_modal_background_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chancecard',
            name='money_deduction_when_wrong_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='musicsetting',
            name='volume_wrong_answer',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='musicsetting',
            name='wrong_answer',
            field=models.CharField(blank=True, default='預設', max_length=500),
        ),
    ]
