# Generated by Django 3.2.5 on 2021-10-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0098_backgroundsetting_modal_background_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicsetting',
            name='modal_background_img_url',
        ),
    ]
