# Generated by Django 3.2.5 on 2021-10-27 08:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0099_remove_basicsetting_modal_background_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsetting',
            name='land_background_color',
            field=colorfield.fields.ColorField(blank=True, default='#cde6d0', max_length=18, null=True),
        ),
    ]
