# Generated by Django 3.2.5 on 2021-10-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0103_alter_land_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefinevariablename',
            name='is_variable_1_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdefinevariablename',
            name='is_variable_2_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdefinevariablename',
            name='is_variable_3_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdefinevariablename',
            name='is_variable_4_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdefinevariablename',
            name='is_variable_5_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.CharField(blank=True, default='台北市', help_text='請輸入土地的描述', max_length=10),
        ),
    ]
