# Generated by Django 3.2.5 on 2021-10-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0104_auto_20211030_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_1_default',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_2_default',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_3_default',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_4_default',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdefinevariablename',
            name='variable_5_default',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
