# Generated by Django 3.2.5 on 2021-12-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0107_auto_20211201_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicsetting',
            name='money_pass_start',
            field=models.CharField(default='2000', max_length=100),
        ),
    ]
