# Generated by Django 3.2.5 on 2021-12-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0109_profile_user_secret_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_secret_code',
        ),
    ]
